### ISSUE TITLE
GLFW Tokens Renamed, Breaks Build Process

### ISSUE THREAD

**Issue by elmarquez** [tenko/gltools#2]
I'm working on Ubuntu 12.04. I have Python 2.7.3, cython 0.7.13, and freeglut3 2.6.0-1 OpenGL headers installed. I've compiled and installed glfw 3.0 from the development branch on the Github site, compiled and installed geotools, and placed the geotools.pxd file in the gltools/gltools subdirectory. I then try to build gltools and get the following:

_@_:/usr/src/gltools$ sudo python setup_build.py build 
running build
running build_ext
skipping 'gltools/gltools.cpp' Cython extension (up-to-date)
building 'gltools' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/gltools
creating build/temp.linux-x86_64-2.7/gltools/@src
creating build/temp.linux-x86_64-2.7/gltools/@contrib
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Igltools/@include -Igltools/@src -Igltools/@contrib -I/usr/include/python2.7 -c gltools/gltools.cpp -o build/temp.linux-x86_64-2.7/gltools/gltools.o -fpermissive
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
gltools/gltools.cpp: In function ‘PyObject\* newarrayobject(PyTypeObject_, Py_ssize_t, arraydescr_)’:
gltools/gltools.cpp:1737:9: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
gltools/gltools.cpp: In function ‘int **pyx_pf_7gltools_6Window___init**(__pyx_obj_7gltools_Window_, int, int, PyObject_, int)’:
gltools/gltools.cpp:5181:18: error: ‘GLFW_OPENGL_VERSION_MAJOR’ was not declared in this scope
gltools/gltools.cpp:5190:18: error: ‘GLFW_OPENGL_VERSION_MINOR’ was not declared in this scope
gltools/gltools.cpp: In function ‘PyObject_ __pyx_f_7gltools_DrawElements(unsigned int, int, int, PyObject*, int)’:
gltools/gltools.cpp:17030:74: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
gltools/@include/GLTools.h: At global scope:
gltools/@include/GLTools.h:32:41: warning: ‘pglActiveTexture’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:33:41: warning: ‘pglGenBuffers’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:34:41: warning: ‘pglDeleteBuffers’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:35:41: warning: ‘pglCreateShader’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:36:41: warning: ‘pglShaderSource’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:37:41: warning: ‘pglCompileShader’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:38:41: warning: ‘pglGetShaderiv’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:39:41: warning: ‘pglGetShaderInfoLog’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:40:41: warning: ‘pglDeleteShader’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:41:41: warning: ‘pglCreateProgram’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:42:41: warning: ‘pglAttachShader’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:43:41: warning: ‘pglLinkProgram’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:44:41: warning: ‘pglUseProgram’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:45:41: warning: ‘pglGetProgramiv’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:46:41: warning: ‘pglGetProgramInfoLog’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:47:41: warning: ‘pglDeleteProgram’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:48:41: warning: ‘pglGetUniformLocation’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:49:41: warning: ‘pglUniform1i’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:50:41: warning: ‘pglUniform1f’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:51:41: warning: ‘pglUniform4f’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:52:41: warning: ‘pglUniformMatrix4fv’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:53:41: warning: ‘pglGetAttribLocation’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:54:41: warning: ‘pglBufferData’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:55:41: warning: ‘pglBindBuffer’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:56:41: warning: ‘pglBufferSubData’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:57:41: warning: ‘pglGetBufferParameteriv’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:58:41: warning: ‘pglEnableVertexAttribArray’ defined but not used [-Wunused-variable]
gltools/@include/GLTools.h:59:41: warning: ‘pglVertexAttribPointer’ defined but not used [-Wunused-variable]
Traceback
:error: command 'gcc' failed with exit status 1

It appears that the GLFW_OPENGL_VERSION_MAJOR and GLFW_OPENGL_VERSION_MINOR tokens have been renamed.

  https://github.com/elmindreda/glfw/commit/3f5843f

**Comment by tenko** [comment]
It seems to me the GLFW head revision is in a state of transit which breaks the API
and renames some constants.

Could you try to check out an earlier commit:

```
 git checkout  06e7a96c61d6013f7717c8a616b7e9c26bb2186b
```

This is the commit i use which is dated Thu Nov 22 19:14:27 2012.
This commit is quite stable in my experience.
I will wait a bit to update the code until I see that the changes seems
to be finished.

**Comment by elmarquez** [comment]
As expected, it builds fine with the prior version. Thanks.

**Comment by tenko** [comment]
On 02/17/2013 09:59 AM, Davis Marques wrote:

> As expected, it builds fine with the prior version. Thanks.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/tenko/gltools/issues/2#issuecomment-13682905.
> 
> Hi,

You are welcome. Please also note that there are
an important fix in the github version of "geotools"
which fixed the camera rotation bug. I recommend
"geotools" is built from the latest github version.
One last bug remain in the camera related to the
calculation of near/far plans which I hope to fix
shortly.

Runar

## 

Tenko as
Notenesgata 1
6002 Ålesund, Norway
Runar Tenfjord (+47) 404 360 81
mailto:office@tenko.no
http://www.tenko.no/

Notice of confidentiality
This transmission is intended for the named addressee only.
It contains information which may be confidential and that
may also be privileged.Unless you are the named addressee
(or authorised to receive it of the addressee) you may not
copy or use it, or disclose it to anyone else.If you have
received this transmission in error, please notify the
sender immediately.
